# Generated by Django 3.0.2 on 2020-03-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0002_auto_20200327_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warden',
        ),
    ]
