# Generated by Django 3.0.2 on 2020-03-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_student_no_dues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='course',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='warden',
            name='hostel',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Hostel',
        ),
    ]
