# Generated by Django 3.0.2 on 2020-03-27 13:54

from django.db import migrations


class Migration(migrations.Migration):
	atomic = False
	dependencies = [('selection', '0003_delete_warden'),]
	operations = [migrations.RenameModel(old_name='Room',new_name='Seat',),]
