# Generated by Django 3.0.2 on 2020-03-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0006_auto_20200324_0036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Passenger',
        ),
    ]
