# Generated by Django 3.0.2 on 2020-03-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0007_auto_20200329_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='password', max_length=20),
        ),
    ]
