# Generated by Django 3.0.2 on 2020-03-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0009_auto_20200329_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='password', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
